Desafio01/Desafio01WebApp/Models/Dtos/UrlDesafio.cs
namespace Desafio01WebApp.Models.Dtos
{
    public class UrlDesafio
    {
        public string Message { get; set; }
        public string ImageUrl { get; set; }
    }
}

Desafio01/Desafio01WebApp/Models/ErrorViewModel.cs
namespace Desafio01WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Desafio01/Desafio01WebApp/Models/Infrastructure/Client/ClientPesquisaHttp.cs
using Desafio01WebApp.Models.Dtos;
using Newtonsoft.Json;

namespace Desafio01WebApp.Models.Infrastructure.Client
{
    public class ClientPesquisaHttp : IClientPesquisaHttp
    {
        public async Task<UrlDesafio> Get(string url, string parametro)
        {
            try
            {
                HttpClient client = new HttpClient();

                var urlBase = $"{url}/{parametro}";
                client.BaseAddress = new Uri(urlBase);
                HttpResponseMessage response = await client.GetAsync(urlBase);

                var content = response.Content.ReadAsStringAsync().Result;
                var result = JsonConvert.DeserializeObject<UrlDesafio>(content);
                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Desafio01/Desafio01WebApp/Models/Infrastructure/Client/IClientPesquisaHttp.cs
using Desafio01WebApp.Models.Dtos;

namespace Desafio01WebApp.Models.Infrastructure.Client
{
    public interface IClientPesquisaHttp
    {
        Task<UrlDesafio> Get(string url, string parametro);
    }
}

Desafio01/Desafio01WebApp/Models/Infrastructure/Repositories/DesafioRepository.cs
using Npgsql;
using System.Data;

namespace Desafio01WebApp.Models.Infrastructure.Repositories
{
    public class DesafioRepository : IDesafioRepository, IDisposable
    {
        private static NpgsqlConnection cn = null;

        public string Execute(string query, string connectionString)
        {
            string result = null;
            NpgsqlCommand cmd = null;
            DataSet ds = null;
            NpgsqlDataAdapter da = null;

            try
            {
                if (cn == null)
                    cn = new NpgsqlConnection(connectionString);

                cmd = new NpgsqlCommand(query, cn);
                ds = new DataSet();
                da = new NpgsqlDataAdapter(cmd);
                da.Fill(ds);

                foreach (DataRow item in ds.Tables[0].Rows)
                {
                    result = item.ItemArray[0].ToString();
                }

                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                cmd = null;
                ds = null;
                da = null;
            }
        }

        public void Dispose()
        {
            cn = null;
        }

    }
}

Desafio01/Desafio01WebApp/Models/Infrastructure/Repositories/IDesafioRepository.cs
namespace Desafio01WebApp.Models.Infrastructure.Repositories
{
    public interface IDesafioRepository
    {

        string Execute(string query, string connectionString);
    }
}

Desafio01/Desafio01WebApp/Models/IoC/DesafioDependencieConfiguration.cs
using Desafio01WebApp.Models.Infrastructure.Client;
using Desafio01WebApp.Models.Infrastructure.Repositories;

namespace Desafio01WebApp.Models.IoC
{
    public class DesafioDependencieConfiguration
    {
        public static void Configure(IServiceCollection services)
        {
            services.AddSingleton<IDesafioRepository, DesafioRepository>();
            services.AddSingleton<IClientPesquisaHttp, ClientPesquisaHttp>();
        }
    }
}

Desafio01/Desafio01WebApp/Controllers/DesafioController.cs
using Desafio01WebApp.Models.Dtos;
using Desafio01WebApp.Models.Infrastructure.Client;
using Desafio01WebApp.Models.Infrastructure.Repositories;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Npgsql;
using System.Data;

namespace Desafio01WebApp.Controllers
{
    public class DesafioController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly IDesafioRepository _desafioRepository;
        private readonly IClientPesquisaHttp _clientPesquisaHttp;

        private static string URL_BASE_01 = $"https://fiap-dotnet.azurewebsites.net/Fiap";
        private static string URL_BASE_02 = $"https://fiap-dotnet.azurewebsites.net/Power";

        public DesafioController(
            IConfiguration configuration,
            IDesafioRepository desafioRepository,
            IClientPesquisaHttp clientPesquisaHttp)
        {
            this.configuration = configuration;
            _desafioRepository = desafioRepository;
            _clientPesquisaHttp = clientPesquisaHttp;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            string connStr = configuration.GetConnectionString("desafiodb");
            var query = configuration["QuerySql:Query_01"];

            try
            {
                var param = _desafioRepository.Execute(query, connStr);

                UrlDesafio response01 = await _clientPesquisaHttp.Get(URL_BASE_01, param);
                UrlDesafio response02 = await _clientPesquisaHttp.Get(URL_BASE_02, response01.Message);
                return View(response02);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }
}

Desafio01/Desafio01WebApp/Controllers/HomeController.cs
using Desafio01WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Desafio01WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Desafio01/Desafio01WebApp/Views/Desafio/Index.cshtml
@model Desafio01WebApp.Models.Dtos.UrlDesafio

@{
    ViewData["Title"] = "Index";
}

<div>
    <h4>Desafio hack 01 PosTech</h4>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            <img src="@Html.DisplayFor(model => model.ImageUrl)" alt="@Html.DisplayFor(model => model.ImageUrl)" />
        </dd>
    </dl>
</div>

Desafio01/Desafio01WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Desafio01/Desafio01WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Desafio01WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Desafio01WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Desafio01WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Desafio" asp-action="Index">Desafio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Desafio01 - andreleaos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>